// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TexasHoldemPoker.API.Models;

#nullable disable

namespace TexasHoldemPoker.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250603154304_AddLeaderboardView")]
    partial class AddLeaderboardView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("Suit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("CardId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.ChipTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex(new[] { "UserId" }, "IX_ChipTransactions_UserId");

                    b.ToTable("ChipTransactions");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.CommunityCard", b =>
                {
                    b.Property<int>("CommunityCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommunityCardId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("GameRoundId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("CommunityCardId");

                    b.HasIndex("CardId");

                    b.HasIndex(new[] { "GameRoundId", "Position" }, "UQ_CommunityCards_GamePosition")
                        .IsUnique();

                    b.ToTable("CommunityCards");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<int?>("CurrentTurnPlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int>("PotSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("CurrentTurnPlayerId");

                    b.HasIndex(new[] { "TableId" }, "IX_Games_TableId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.GamePlayer", b =>
                {
                    b.Property<int>("GamePlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GamePlayerId"));

                    b.Property<int>("CurrentChips")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("InitialChips")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBigBlind")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDealer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmallBlind")
                        .HasColumnType("bit");

                    b.Property<int>("SeatPosition")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GamePlayerId");

                    b.HasIndex(new[] { "GameId" }, "IX_GamePlayers_GameId");

                    b.HasIndex(new[] { "UserId" }, "IX_GamePlayers_UserId");

                    b.HasIndex(new[] { "GameId", "SeatPosition" }, "UQ_GamePlayers_GamePosition")
                        .IsUnique();

                    b.HasIndex(new[] { "GameId", "UserId" }, "UQ_GamePlayers_GameUser")
                        .IsUnique();

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.GameRound", b =>
                {
                    b.Property<int>("GameRoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameRoundId"));

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PotSize")
                        .HasColumnType("int");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("GameRoundId");

                    b.HasIndex("GameId");

                    b.ToTable("GameRounds");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.GameRoundWinner", b =>
                {
                    b.Property<int>("GameRoundWinnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameRoundWinnerId"));

                    b.Property<int>("AmountWon")
                        .HasColumnType("int");

                    b.Property<int>("GameRoundId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GameRoundWinnerId");

                    b.HasIndex("GameRoundId");

                    b.HasIndex("UserId");

                    b.ToTable("GameRoundWinners");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.LeaderboardView", b =>
                {
                    b.Property<string>("AvatarImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ChipsBalance")
                        .HasColumnType("int");

                    b.Property<int?>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int?>("GamesWon")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("WinRatio")
                        .HasColumnType("float");

                    b.ToTable((string)null);

                    b.ToView("LeaderboardView", (string)null);
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<string>("Difficulty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Path")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ModelId");

                    b.HasIndex(new[] { "Name" }, "UQ_Models_Name")
                        .IsUnique();

                    b.ToTable("Models");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Move", b =>
                {
                    b.Property<int>("MoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoveId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("GameRoundId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MoveTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MoveId");

                    b.HasIndex("GameRoundId");

                    b.HasIndex(new[] { "PlayerId" }, "IX_Moves_PlayerId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.PlayerCard", b =>
                {
                    b.Property<int>("PlayerCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerCardId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("GamePlayerId")
                        .HasColumnType("int");

                    b.Property<int>("GameRoundId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PlayerCardId");

                    b.HasIndex("CardId");

                    b.HasIndex("GamePlayerId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "GameRoundId", "GamePlayerId", "Position" }, "UQ_PlayerCards_GamePlayerPosition")
                        .IsUnique();

                    b.ToTable("PlayerCards");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.PokerTable", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int>("BigBlind")
                        .HasColumnType("int");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EntryFee")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxBuyIn")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlayers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4);

                    b.Property<int>("MinBuyIn")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SmallBlind")
                        .HasColumnType("int");

                    b.HasKey("TableId");

                    b.ToTable("PokerTables");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PurchaseId");

                    b.HasIndex("ItemId");

                    b.HasIndex(new[] { "UserId" }, "IX_Purchases_UserId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.ShopItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("PLN");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ItemId");

                    b.ToTable("ShopItems");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AvatarType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Standard");

                    b.Property<int>("ChipsBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5000);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsBot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ_Users_Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.UserModel", b =>
                {
                    b.Property<int>("UserModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserModelId"));

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserModelId");

                    b.HasIndex("ModelId");

                    b.HasIndex("UserId");

                    b.ToTable("UserModels");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.ChipTransaction", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.User", "User")
                        .WithMany("ChipTransactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ChipTransactions_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.CommunityCard", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.Card", "Card")
                        .WithMany("CommunityCards")
                        .HasForeignKey("CardId")
                        .IsRequired()
                        .HasConstraintName("FK_CommunityCards_Cards");

                    b.HasOne("TexasHoldemPoker.API.Models.GameRound", "GameRound")
                        .WithMany("CommunityCards")
                        .HasForeignKey("GameRoundId")
                        .IsRequired()
                        .HasConstraintName("FK_CommunityCards_GameRounds");

                    b.Navigation("Card");

                    b.Navigation("GameRound");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Game", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.GamePlayer", "CurrentTurnPlayer")
                        .WithMany("Games")
                        .HasForeignKey("CurrentTurnPlayerId")
                        .HasConstraintName("FK_Games_GamePlayers");

                    b.HasOne("TexasHoldemPoker.API.Models.PokerTable", "Table")
                        .WithMany("Games")
                        .HasForeignKey("TableId")
                        .IsRequired()
                        .HasConstraintName("FK_Games_PokerTables");

                    b.Navigation("CurrentTurnPlayer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.GamePlayer", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.Game", "Game")
                        .WithMany("GamePlayers")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("FK_GamePlayers_Games");

                    b.HasOne("TexasHoldemPoker.API.Models.User", "User")
                        .WithMany("GamePlayers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_GamePlayers_Users");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.GameRound", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.Game", "Game")
                        .WithMany("GameRounds")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("FK_GameRounds_Games");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.GameRoundWinner", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.GameRound", "GameRound")
                        .WithMany("GameRoundWinners")
                        .HasForeignKey("GameRoundId")
                        .IsRequired()
                        .HasConstraintName("FK_GameRoundWinners_GameRounds");

                    b.HasOne("TexasHoldemPoker.API.Models.User", "User")
                        .WithMany("GameRoundWinners")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_GameRoundWinners_Users");

                    b.Navigation("GameRound");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Move", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.GameRound", "GameRound")
                        .WithMany("Moves")
                        .HasForeignKey("GameRoundId")
                        .IsRequired()
                        .HasConstraintName("FK_Moves_GameRounds");

                    b.HasOne("TexasHoldemPoker.API.Models.User", "Player")
                        .WithMany("Moves")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK_Moves_Users");

                    b.Navigation("GameRound");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.PlayerCard", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.Card", "Card")
                        .WithMany("PlayerCards")
                        .HasForeignKey("CardId")
                        .IsRequired()
                        .HasConstraintName("FK_PlayerCards_Cards");

                    b.HasOne("TexasHoldemPoker.API.Models.GamePlayer", "GamePlayer")
                        .WithMany("PlayerCards")
                        .HasForeignKey("GamePlayerId")
                        .IsRequired()
                        .HasConstraintName("FK_PlayerCards_GamePlayers");

                    b.HasOne("TexasHoldemPoker.API.Models.GameRound", "GameRound")
                        .WithMany("PlayerCards")
                        .HasForeignKey("GameRoundId")
                        .IsRequired()
                        .HasConstraintName("FK_PlayerCards_GameRounds");

                    b.HasOne("TexasHoldemPoker.API.Models.User", "User")
                        .WithMany("PlayerCards")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_PlayerCards_Users");

                    b.Navigation("Card");

                    b.Navigation("GamePlayer");

                    b.Navigation("GameRound");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Purchase", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.ShopItem", "Item")
                        .WithMany("Purchases")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_Purchases_ShopItems");

                    b.HasOne("TexasHoldemPoker.API.Models.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Purchases_Users");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.UserModel", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.Model", "Model")
                        .WithMany("UserModels")
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("FK_UserModels_Models");

                    b.HasOne("TexasHoldemPoker.API.Models.User", "User")
                        .WithMany("UserModels")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserModels_Users");

                    b.Navigation("Model");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Card", b =>
                {
                    b.Navigation("CommunityCards");

                    b.Navigation("PlayerCards");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Game", b =>
                {
                    b.Navigation("GamePlayers");

                    b.Navigation("GameRounds");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.GamePlayer", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("PlayerCards");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.GameRound", b =>
                {
                    b.Navigation("CommunityCards");

                    b.Navigation("GameRoundWinners");

                    b.Navigation("Moves");

                    b.Navigation("PlayerCards");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Model", b =>
                {
                    b.Navigation("UserModels");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.PokerTable", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.ShopItem", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.User", b =>
                {
                    b.Navigation("ChipTransactions");

                    b.Navigation("GamePlayers");

                    b.Navigation("GameRoundWinners");

                    b.Navigation("Moves");

                    b.Navigation("PlayerCards");

                    b.Navigation("Purchases");

                    b.Navigation("UserModels");
                });
#pragma warning restore 612, 618
        }
    }
}
