// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TexasHoldemPoker.API.Data;

#nullable disable

namespace TexasHoldemPoker.API.Migrations
{
    [DbContext(typeof(PokerDbContext))]
    [Migration("20250522203259_AddDifficultyToPokerTable")]
    partial class AddDifficultyToPokerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("Suit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = 1,
                            Suit = "Hearts",
                            Value = "2"
                        },
                        new
                        {
                            CardId = 2,
                            Suit = "Hearts",
                            Value = "3"
                        },
                        new
                        {
                            CardId = 3,
                            Suit = "Hearts",
                            Value = "4"
                        },
                        new
                        {
                            CardId = 4,
                            Suit = "Hearts",
                            Value = "5"
                        },
                        new
                        {
                            CardId = 5,
                            Suit = "Hearts",
                            Value = "6"
                        },
                        new
                        {
                            CardId = 6,
                            Suit = "Hearts",
                            Value = "7"
                        },
                        new
                        {
                            CardId = 7,
                            Suit = "Hearts",
                            Value = "8"
                        },
                        new
                        {
                            CardId = 8,
                            Suit = "Hearts",
                            Value = "9"
                        },
                        new
                        {
                            CardId = 9,
                            Suit = "Hearts",
                            Value = "10"
                        },
                        new
                        {
                            CardId = 10,
                            Suit = "Hearts",
                            Value = "J"
                        },
                        new
                        {
                            CardId = 11,
                            Suit = "Hearts",
                            Value = "Q"
                        },
                        new
                        {
                            CardId = 12,
                            Suit = "Hearts",
                            Value = "K"
                        },
                        new
                        {
                            CardId = 13,
                            Suit = "Hearts",
                            Value = "A"
                        },
                        new
                        {
                            CardId = 14,
                            Suit = "Diamonds",
                            Value = "2"
                        },
                        new
                        {
                            CardId = 15,
                            Suit = "Diamonds",
                            Value = "3"
                        },
                        new
                        {
                            CardId = 16,
                            Suit = "Diamonds",
                            Value = "4"
                        },
                        new
                        {
                            CardId = 17,
                            Suit = "Diamonds",
                            Value = "5"
                        },
                        new
                        {
                            CardId = 18,
                            Suit = "Diamonds",
                            Value = "6"
                        },
                        new
                        {
                            CardId = 19,
                            Suit = "Diamonds",
                            Value = "7"
                        },
                        new
                        {
                            CardId = 20,
                            Suit = "Diamonds",
                            Value = "8"
                        },
                        new
                        {
                            CardId = 21,
                            Suit = "Diamonds",
                            Value = "9"
                        },
                        new
                        {
                            CardId = 22,
                            Suit = "Diamonds",
                            Value = "10"
                        },
                        new
                        {
                            CardId = 23,
                            Suit = "Diamonds",
                            Value = "J"
                        },
                        new
                        {
                            CardId = 24,
                            Suit = "Diamonds",
                            Value = "Q"
                        },
                        new
                        {
                            CardId = 25,
                            Suit = "Diamonds",
                            Value = "K"
                        },
                        new
                        {
                            CardId = 26,
                            Suit = "Diamonds",
                            Value = "A"
                        },
                        new
                        {
                            CardId = 27,
                            Suit = "Clubs",
                            Value = "2"
                        },
                        new
                        {
                            CardId = 28,
                            Suit = "Clubs",
                            Value = "3"
                        },
                        new
                        {
                            CardId = 29,
                            Suit = "Clubs",
                            Value = "4"
                        },
                        new
                        {
                            CardId = 30,
                            Suit = "Clubs",
                            Value = "5"
                        },
                        new
                        {
                            CardId = 31,
                            Suit = "Clubs",
                            Value = "6"
                        },
                        new
                        {
                            CardId = 32,
                            Suit = "Clubs",
                            Value = "7"
                        },
                        new
                        {
                            CardId = 33,
                            Suit = "Clubs",
                            Value = "8"
                        },
                        new
                        {
                            CardId = 34,
                            Suit = "Clubs",
                            Value = "9"
                        },
                        new
                        {
                            CardId = 35,
                            Suit = "Clubs",
                            Value = "10"
                        },
                        new
                        {
                            CardId = 36,
                            Suit = "Clubs",
                            Value = "J"
                        },
                        new
                        {
                            CardId = 37,
                            Suit = "Clubs",
                            Value = "Q"
                        },
                        new
                        {
                            CardId = 38,
                            Suit = "Clubs",
                            Value = "K"
                        },
                        new
                        {
                            CardId = 39,
                            Suit = "Clubs",
                            Value = "A"
                        },
                        new
                        {
                            CardId = 40,
                            Suit = "Spades",
                            Value = "2"
                        },
                        new
                        {
                            CardId = 41,
                            Suit = "Spades",
                            Value = "3"
                        },
                        new
                        {
                            CardId = 42,
                            Suit = "Spades",
                            Value = "4"
                        },
                        new
                        {
                            CardId = 43,
                            Suit = "Spades",
                            Value = "5"
                        },
                        new
                        {
                            CardId = 44,
                            Suit = "Spades",
                            Value = "6"
                        },
                        new
                        {
                            CardId = 45,
                            Suit = "Spades",
                            Value = "7"
                        },
                        new
                        {
                            CardId = 46,
                            Suit = "Spades",
                            Value = "8"
                        },
                        new
                        {
                            CardId = 47,
                            Suit = "Spades",
                            Value = "9"
                        },
                        new
                        {
                            CardId = 48,
                            Suit = "Spades",
                            Value = "10"
                        },
                        new
                        {
                            CardId = 49,
                            Suit = "Spades",
                            Value = "J"
                        },
                        new
                        {
                            CardId = 50,
                            Suit = "Spades",
                            Value = "Q"
                        },
                        new
                        {
                            CardId = 51,
                            Suit = "Spades",
                            Value = "K"
                        },
                        new
                        {
                            CardId = 52,
                            Suit = "Spades",
                            Value = "A"
                        });
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.ChipTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("ChipTransactions");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.CommunityCard", b =>
                {
                    b.Property<int>("CommunityCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommunityCardId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("CommunityCardId");

                    b.HasIndex("CardId");

                    b.HasIndex("GameId", "Position")
                        .IsUnique();

                    b.ToTable("CommunityCards");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PotSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("TableId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.GamePlayer", b =>
                {
                    b.Property<int>("GamePlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GamePlayerId"));

                    b.Property<int>("CurrentChips")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("InitialChips")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBigBlind")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDealer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmallBlind")
                        .HasColumnType("bit");

                    b.Property<int>("SeatPosition")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GamePlayerId");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "SeatPosition")
                        .IsUnique();

                    b.HasIndex("GameId", "UserId")
                        .IsUnique();

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.LeaderboardEntry", b =>
                {
                    b.Property<string>("AvatarImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChipsBalance")
                        .HasColumnType("int");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("GamesWon")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WinRatio")
                        .HasColumnType("float");

                    b.ToTable((string)null);

                    b.ToView("LeaderboardView", (string)null);
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Move", b =>
                {
                    b.Property<int>("MoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoveId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MoveTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MoveId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.PlayerCard", b =>
                {
                    b.Property<int>("PlayerCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerCardId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("GamePlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("PlayerCardId");

                    b.HasIndex("CardId");

                    b.HasIndex("GamePlayerId", "Position")
                        .IsUnique();

                    b.ToTable("PlayerCards");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.PokerTable", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int>("BigBlind")
                        .HasColumnType("int");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntryFee")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxBuyIn")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<int>("MinBuyIn")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmallBlind")
                        .HasColumnType("int");

                    b.HasKey("TableId");

                    b.ToTable("PokerTables");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            BigBlind = 20,
                            DifficultyLevel = "Beginner",
                            EntryFee = 100,
                            IsActive = true,
                            MaxBuyIn = 1000,
                            MaxPlayers = 9,
                            MinBuyIn = 500,
                            Name = "Beginner Table",
                            SmallBlind = 10
                        },
                        new
                        {
                            TableId = 2,
                            BigBlind = 100,
                            DifficultyLevel = "Intermediate",
                            EntryFee = 500,
                            IsActive = true,
                            MaxBuyIn = 5000,
                            MaxPlayers = 9,
                            MinBuyIn = 1000,
                            Name = "Intermediate Table",
                            SmallBlind = 50
                        },
                        new
                        {
                            TableId = 3,
                            BigBlind = 200,
                            DifficultyLevel = "Pro",
                            EntryFee = 1000,
                            IsActive = true,
                            MaxBuyIn = 10000,
                            MaxPlayers = 9,
                            MinBuyIn = 5000,
                            Name = "Pro Table",
                            SmallBlind = 100
                        });
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PurchaseId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.ShopItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemId");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Currency = "PLN",
                            Description = "Unlock a premium avatar for your profile.",
                            IsActive = true,
                            ItemType = "Avatar",
                            Name = "Premium Avatar",
                            Price = 9.99m
                        },
                        new
                        {
                            ItemId = 2,
                            Currency = "PLN",
                            Description = "Unlock a golden avatar.",
                            IsActive = true,
                            ItemType = "Avatar",
                            Name = "Golden Avatar",
                            Price = 14.99m
                        },
                        new
                        {
                            ItemId = 3,
                            Currency = "CHIPS",
                            Description = "Get 1000 chips.",
                            IsActive = true,
                            ItemType = "Chips",
                            Name = "Basic Chips Pack",
                            Price = 1000m
                        });
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChipsBalance")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.ChipTransaction", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.User", "User")
                        .WithMany("ChipTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.CommunityCard", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.Card", "Card")
                        .WithMany("CommunityCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TexasHoldemPoker.API.Models.Game", "Game")
                        .WithMany("CommunityCards")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Game", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.PokerTable", "Table")
                        .WithMany("Games")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TexasHoldemPoker.API.Models.User", "Winner")
                        .WithMany("WonGames")
                        .HasForeignKey("WinnerId");

                    b.Navigation("Table");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.GamePlayer", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.Game", "Game")
                        .WithMany("GamePlayers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TexasHoldemPoker.API.Models.User", "User")
                        .WithMany("GamePlayers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Move", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.Game", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TexasHoldemPoker.API.Models.User", "Player")
                        .WithMany("Moves")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.PlayerCard", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.Card", "Card")
                        .WithMany("PlayerCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TexasHoldemPoker.API.Models.GamePlayer", "GamePlayer")
                        .WithMany("PlayerCards")
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("GamePlayer");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Purchase", b =>
                {
                    b.HasOne("TexasHoldemPoker.API.Models.ShopItem", "Item")
                        .WithMany("Purchases")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TexasHoldemPoker.API.Models.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Card", b =>
                {
                    b.Navigation("CommunityCards");

                    b.Navigation("PlayerCards");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.Game", b =>
                {
                    b.Navigation("CommunityCards");

                    b.Navigation("GamePlayers");

                    b.Navigation("Moves");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.GamePlayer", b =>
                {
                    b.Navigation("PlayerCards");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.PokerTable", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.ShopItem", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("TexasHoldemPoker.API.Models.User", b =>
                {
                    b.Navigation("ChipTransactions");

                    b.Navigation("GamePlayers");

                    b.Navigation("Moves");

                    b.Navigation("Purchases");

                    b.Navigation("WonGames");
                });
#pragma warning restore 612, 618
        }
    }
}
